targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        options:
        generate_for:
          - lib/**_page.dart
          - lib/**router.dart
      auto_route_generator:auto_router_generator:
        generate_for:
          - lib/**router.dart
