name: hotel_booking
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  dio: ^5.7.0
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  auto_route: ^9.2.2
  get_it: ^8.0.2
  flutter_native_splash: ^2.4.3
  icons_launcher: ^3.0.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  image_picker:
  freezed_annotation: ^3.0.0
  shared_preferences: ^2.5.2
  lucide_icons:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # Code Generation
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  auto_route_generator: ^9.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android_12:
    image: assets/logo.png
    color: "#ffffff"
    icon_background_color: "#ffffff"
  ios: true
  web: false

icons_launcher:
  image_path: "assets/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true